### 获取二维码列表
GET http://127.0.0.1:33001/api/qrcode/list
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer xxx

### 获取单个二维码详情信息
GET http://127.0.0.1:33001/api/qrcode/detail?qrcodeId=
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer xxx

### 创建二维码
POST http://127.0.0.1:33001/api/qrcode/create
Content-Type: application/json
Authorization: Bearer xxx

{
    "name": "",
    "description": "",
    "url": ""
}

### 更新二维码
POST http://127.0.0.1:33001/api/qrcode/update
Content-Type: application/json
Authorization: Bearer xxx

{
    "qrcodeId": "",
    "name": "",
    "description": "",
    "url": ""
}

### 删除二维码
DELETE http://127.0.0.1:33001/api/qrcode/delete
Content-Type: application/json
Authorization: Bearer xxx

{
    "qrcodeId": ""
}
